version: '3.9'

services:
  astro:
    restart: unless-stopped
    volumes:
      - ./PortalsAstroRmk:/app
    build:
      context: ./PortalsAstroRmk
      dockerfile: ./docker/dev.dockerfile
    ports:
      - "4321:4321"
    environment:
      - BACKEND_URL_REST=http://YOUR_IP_ADRRES:3000 ####### edit
      - WEBSOCKET_URL=http://YOUR_IP_ADRRES:5000 ####### edit

  restapi:
    depends_on:
      - mongo
    build: ./PortalsServerRmk
    ports:
      - "3000:3000"
    entrypoint: ["sh", "entrypoint.sh"]
    environment:
      - DB_URI=mongodb://YOUR_IP_ADRRES:27027/ ####### edit
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPassXXX
    restart: unless-stopped

  websocket:
    depends_on:
      - mongo
    build: ./PortalsWebSocket
    ports:
      - "5000:5000"
    entrypoint: ["sh", "entrypoint.sh"]
    environment:
      - DB_URI=mongodb://YOUR_IP_ADRRES:27027/ ####### edit
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPassXXX
    restart: unless-stopped

  mongo:
    image: mongo
    ports:
      - "27027:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPassXXX
    attach: false
    restart: unless-stopped