version: '3.9'

services:
  astro:
    build:
      context: ./PortalsAstroRmk
      dockerfile: ./docker/dev.dockerfile
    ports:
      - "4321:4321"
    environment:
      - BACKEND_URL_REST=http://YOUR_IP_ADDRES:3000 ########## edit

  restapi:
    depends_on:
      - mongo
    build: ./PortalsServerRmk
    ports:
      - "3000:3000"
    entrypoint: ["sh", "entrypoint.sh"]
    environment:
      - DB_URI=mongodb://YOUR_IP_ADDRES:27017/ ########## edit
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPassXXX

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPassXXX